name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          password: ${{ secrets.PASSWORD }}

          script: |
            cd /var/www/we_drive_dashboard
            git restore .
            git pull origin master
            sudo su
            npm i
            npm run build
            pm2 restart 0
